language: node_js
before_script:
  - npm install -g gulp-cli
script:
  - gulp build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as an environment variable
    keep-history: false
    local-dir: dist/
    repo: quicksign/dev
    on:
      branch: develop
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as an environment variable
    keep-history: false
    local-dir: dist/
    target-branch: master
    on:
      branch: prod
